# Generated by Django 4.2.3 on 2023-07-28 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=None, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_like',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='art_sharing_app.artwork'),
        ),
    ]
