# Generated by Django 4.2.3 on 2023-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_sharing_app', '0002_remove_artwork_likes_count_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='num_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
