# Generated by Django 4.2.3 on 2023-07-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_sharing_app', '0005_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
