# Generated by Django 4.2.3 on 2023-08-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_sharing_app', '0008_tiesprof'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiesprof',
            name='name',
            field=models.CharField(default='TIEs', max_length=200),
        ),
    ]
