# Generated by Django 4.2.3 on 2023-08-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_sharing_app', '0009_tiesprof_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TIEsProf',
            new_name='TiesLogo',
        ),
    ]
