# Generated by Django 4.2.3 on 2023-08-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_sharing_app', '0012_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='logo/TIEs 20230802_125509.jpg', upload_to='profile'),
        ),
    ]
